// apps/react-app/src/App.tsx
import { useState } from 'react'
import './App.css'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="micro-app micro-app--react">
      <span className="micro-app__badge">React 19</span>
      <h1>React 子应用</h1>
      <p>可独立运行，也可通过 bootstrap / mount / unmount 接入微前端基座。</p>
      <button type="button" onClick={() => setCount((c) => c + 1)}>
        Count: {count}
      </button>
    </div>
  )
}

export default App

// apps/vue-app/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)
</script>

<template>
  <div class="micro-app micro-app--vue">
    <span class="micro-app__badge">Vue 3</span>
    <h1>Vue 子应用</h1>
    <p>可独立运行，也可通过 bootstrap / mount / unmount 接入微前端基座。</p>
    <button type="button" @click="count++">Count: {{ count }}</button>
  </div>
</template>
